spring:
  application:
    name: location-service
  config:
    import: optional:configserver:http://localhost:8888
  data:
    mongodb:
      uri: mongodb://localhost:27017/location-service

server:
  port: 8081
