spring:
  application:
    name: queue-service
  datasource:
    url: jdbc:postgresql://localhost:5432/queuedb
    username: postgres
    password: 5555
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8082
